language: groovy

script:
  - echo 'skip'
  - env

deploy:
  - provider: script
    skip_cleanup: true
    script: echo 'deploying feature! or master still works!!!'
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH == master || ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} =~ ^feature\/.*$
  - provider: script
    skip_cleanup: true
    script: echo 'deploying release!!!'
    on:
      all_branches: true
      condition: ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} =~ ^release\/.*$
