language: groovy

script:
  - echo 'skip'

deploy:
  - provider: script
    skip_cleanup: true
    script: echo 'deploying feature!'
    on:
      all_branches: true
      condition: ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} =~ ^feature\/.*$
  - provider: script
    skip_cleanup: true
    script: echo 'deploying release!!!'
    on:
      all_branches: true
      condition: ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} =~ ^release\/.*$
